### ISSUE TITLE
TypeError: Can not find node binding files from @napi-rs/pinyin-linux-x64-gnu

### ISSUE THREAD

**Issue by cll123456** [Brooooooklyn/pinyin#155]
i use this package in my local(windows, `node 14.17.2`) is ok, but when i push  my serve(centos, `node 16.4`) is not ok. The message error as follows:

**TypeError: Can not find node binding files from @napi-rs/pinyin-linux-x64-gnu, @napi-rs/pinyin-linux-x64-gnux32, @napi-rs/pinyin-linux-x64-musl and /usr/local/nginx/html/cll-blog/server/node_modules/@napi-rs/pinyin/pinyin.linux-x64-gnu.node, /usr/local/nginx/html/cll-blog/server/node_modules/@napi-rs/pinyin/pinyin.linux-x64-gnux32.node, /usr/local/nginx/html/cll-blog/server/node_modules/@napi-rs/pinyin/pinyin.linux-x64-musl.node**

![image](https://user-images.githubusercontent.com/41314419/125032899-30fb0800-e0c1-11eb-8ced-a7e233530373.png)

![image](https://user-images.githubusercontent.com/41314419/125033108-78819400-e0c1-11eb-9a4f-fa6593c2e6c3.png)

**Comment by Brooooooklyn** [comment]
CentOS is not supported now, because `Glibc` on it is too old, checkout out this https://github.com/swc-project/swc/issues/1410 for reason.

**Comment by cll123456** [comment]
ok, Thank you for your reply！
