### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by zhaolong06** [Brooooooklyn/pinyin#189]
node_modules/@napi-rs/pinyin/index.d.ts:9:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

9     [K: symbol]: T
       ~

[下午3:54:34] Found 1 error. Watching for file changes.

**Comment by Brooooooklyn** [comment]
Add `skipLibkCheck: true` in your `tsconfig.json` as a workaround

**Comment by zhaolong06** [comment]
> Add `skipLibkCheck: true` in your `tsconfig.json` as a workaround

thanks~
